name: OTP Graph Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Pull LFS data
        run: git lfs pull

      - name: Build OTP Graph
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/var/opentripplanner" \
            -e JAVA_OPTIONS="-Xmx12G" \
            opentripplanner/opentripplanner@sha256:a4e31dea1da0cae08d4efa2428dc4b2e6829fcf17fac3595805bdb3472b3327d --build --save

      - name: Upload Graph Artifact
        uses: actions/upload-artifact@v4
        with:
          name: otp-graph
          path: graph.obj